### ISSUE TITLE
Improve Variable Names

### ISSUE THREAD

**Issue by LedaThemis** [xonin-hush/Odin-Rock-Paper-Scissors#1]
https://github.com/xonin-hush/Odin-Rock-Paper-Scissors/blob/a543c8a379169ab7f0b6cfd2aac82d21057d97a3/rock.js#L16
What's `a` in this case? (userInput, I think, would be more appropriate)

https://github.com/xonin-hush/Odin-Rock-Paper-Scissors/blob/a543c8a379169ab7f0b6cfd2aac82d21057d97a3/rock.js#L22
I get that `p` is supposed to be the player's choice, and `c` the computer choice. (Why not name them `playerChoice` and `computerChoice` for clarity?)

**Comment by xonin-hush** [comment]
Thank you for pointing that out, Will edit ASAP

**Comment by xonin-hush** [comment]
Updated in a63d2a293ad67fd31dde9aa3393ffaaf8b01fad7
